  "addonName": "stormforge_optimize-live",
            "addonName": "eks-pod-identity-agent",v1.3.7-eksbuild.2
            "addonName": "leaksignal_leakagent",
            "addonName": "eks-node-monitoring-agent",
            "addonName": "aws-ebs-csi-driver", v1.44.0-eksbuild.1
            "addonName": "adot",
            "addonName": "uptycs_uptycs-runtime-sensor",
            "addonName": "akuity_agent",
            "addonName": "grafana-labs_kubernetes-monitoring",
            "addonName": "metrics-server", v0.7.2-eksbuild.3
            "addonName": "tetrate-io_istio-distro",
            "addonName": "aws-mountpoint-s3-csi-driver",
            "addonName": "upbound_universal-crossplane",
            "addonName": "suse_observability-agent",
            "addonName": "splunk_splunk-otel-collector-chart",
            "addonName": "netapp_trident-operator",
            "addonName": "solarwinds_swo-k8s-collector-addon",
            "addonName": "kong_konnect-ri",
            "addonName": "cloudsoft_amp-add-on",
            "addonName": "accuknox_kubearmor",
            "addonName": "friendliai_friendli-container",
            "addonName": "solo-io_gloo-gateway",
            "addonName": "new-relic_kubernetes-operator",
            "addonName": "dynatrace_dynatrace-operator",
            "addonName": "aws-guardduty-agent", v1.10.0-eksbuild.2
            "addonName": "kube-proxy",   v1.32.3-eksbuild.7  
            "addonName": "teleport_teleport",
            "addonName": "cisco_cisco-cloud-observability-collectors",
            "addonName": "rad-security_rad-security",
            "addonName": "upwind-security_upwind-operator",
            "addonName": "guance_datakit",
            "addonName": "cisco_cisco-cloud-observability-operators",
            "addonName": "factorhouse_kpow",
            "addonName": "snyk_runtime-sensor",
            "addonName": "nirmata_nirmata-kyverno-payg",
            "addonName": "appviewx_appviewx-mim-eks",
            "addonName": "groundcover_agent",
            "addonName": "haproxy-technologies_kubernetes-ingress-ee",
            "addonName": "coredns",  v1.11.4-eksbuild.14
            "addonName": "kube-state-metrics",
            "addonName": "solodev_cms",
            "addonName": "solo-io_istio-distro",
            "addonName": "rafay-systems_rafay-operator",
            "addonName": "kubecost_kubecost",
            "addonName": "vpc-cni",  v1.19.2-eksbuild.1
            "addonName": "aws-efs-csi-driver",
            "addonName": "cert-manager",v1.17.2-eksbuild.1
            "addonName": "calyptia_fluent-bit",
            "addonName": "prometheus-node-exporter",
            "addonName": "external-dns",
            "addonName": "catalogic-software_cloudcasa",
            "addonName": "uptycs_uptycs-collector",
            "addonName": "aws-fsx-csi-driver",
            "addonName": "elastic_elastic-agent",
            "addonName": "spacelift_workerpool-controller",
            "addonName": "datadog_operator",
            "addonName": "solo-io_gloo-mesh-starter-pack",
            "addonName": "amazon-cloudwatch-observability",v4.0.1-eksbuild.1
            "addonName": "cribl_cribledge",
            "addonName": "nirmata_kyverno",
            "addonName": "snapshot-controller",
            "addonName": "datree_engine-pro",
